server:
  port: 8090

blog:
  name: RippleSu's Blog
  api: http://localhost:${server.port}
  cms: http://localhost:8080
  view: http://localhost:8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 
  redis:
    host: 
    password: 
    port: 6379
    database: 0
    timeout: 1000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1
  mail:
    host: 
    port: 465
    username: 
    password: 

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration.map-underscore-to-camel-case: true

logging:
  file:
    name: blog-api/log/blog-dev
  logging.level.root: info
  logging.level.top.naccl: debug

token:
  expireTime: 259200000
  secretKey: abcdefghijklmnopqrstuvwxyz

comment:
  notify.channel: mail
  default-open: true


upload:
  channel: local
  file:
    path: /Users/rippleSu/blog/upload/
    access-path: /image/**
    resources-locations: file:${upload.file.path}

aliyun:
  accessKeyId: 
  secretAccessKey: 
  oss:
    endPoint: 
    bucketName: 
#tg:
#  bot:
#    api: https://api.telegram.org/bot
#    token: 1234567890:qwertyuiopasdfghjklzxcvbnm
#    chat-id: 1234567890
#    use-proxy: false
#    use-reverse-proxy: true
#    reverse-proxy-url: https://tg-api-open.naccl.workers.dev
#
http.proxy.server.host: 127.0.0.1
http.proxy.server.port: 7890
http.proxy.server.timeout: 10000
# GitHub token \u6559\u7A0B\u89C1 https://naccl.github.io/PictureHosting/#/pictureHosting/help
#upload.github.token: ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#upload.github.username: Naccl
#upload.github.repos: test
#upload.github.repos-path: /comment/avatar

